# Generated by Django 3.1.7 on 2021-03-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0002_auto_20210314_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
