# Generated by Django 3.1.7 on 2021-03-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_module', '0004_auto_20210314_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
