# Generated by Django 3.1.7 on 2021-03-29 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0021_auto_20210326_1304'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compiler_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeProblemResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useroutputone', models.CharField(max_length=20)),
                ('useroutputtwo', models.CharField(max_length=20)),
                ('useroutputthree', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=5000)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_module.practiceproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CodeModel',
        ),
        migrations.AddField(
            model_name='practiceproblemresult',
            name='useroutputonestatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler_module.testcasestatus'),
        ),
    ]
