# Generated by Django 3.1.7 on 2021-03-29 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler_module', '0002_auto_20210329_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproblemresult',
            name='useroutputtwostatus',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='compiler_module.testcasestatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practiceproblemresult',
            name='useroutputonestatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputstatusone', to='compiler_module.testcasestatus'),
        ),
    ]
