# Generated by Django 3.1.7 on 2021-03-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler_module', '0003_auto_20210329_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproblemresult',
            name='useroutputthreestatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outputstatusthree', to='compiler_module.testcasestatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='practiceproblemresult',
            name='useroutputtwostatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputstatustwo', to='compiler_module.testcasestatus'),
        ),
    ]
