# Generated by Django 3.1.7 on 2021-04-03 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compete_module', '0009_auto_20210403_1524'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compiler_module', '0005_auto_20210403_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceproblemresult',
            name='code',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='practiceproblemresult',
            name='useroutputone',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='practiceproblemresult',
            name='useroutputthree',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='practiceproblemresult',
            name='useroutputtwo',
            field=models.TextField(max_length=100),
        ),
        migrations.CreateModel(
            name='CompeteProblemResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useroutputone', models.TextField(max_length=100)),
                ('useroutputtwo', models.TextField(max_length=100)),
                ('useroutputthree', models.TextField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('code', models.TextField(max_length=5000)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete_module.competemodel')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete_module.competitionownproblem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('useroutputonestatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testoutputstatusone', to='compiler_module.testcasestatus')),
                ('useroutputthreestatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testoutputstatusthree', to='compiler_module.testcasestatus')),
                ('useroutputtwostatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testoutputstatustwo', to='compiler_module.testcasestatus')),
            ],
        ),
    ]
