# Generated by Django 3.1.7 on 2021-04-06 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compiler_module', '0006_auto_20210403_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='competeproblemresult',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='practiceproblemresult',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
