# Generated by Django 3.1.7 on 2021-04-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler_module', '0009_auto_20210406_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='competeproblemresult',
            name='testcaseonememory',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='competeproblemresult',
            name='testcaseonetime',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='competeproblemresult',
            name='testcasethreememory',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='competeproblemresult',
            name='testcasethreetime',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='competeproblemresult',
            name='testcasetwomemory',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='competeproblemresult',
            name='testcasetwotime',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
