# Generated by Django 3.1.7 on 2021-04-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institutionprofile',
            old_name='institutionname',
            new_name='institution_name',
        ),
        migrations.RenameField(
            model_name='institutionprofile',
            old_name='phonenumber',
            new_name='phone_number',
        ),
    ]
