# Generated by Django 3.1.7 on 2021-03-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeMainTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintopic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=250)),
                ('maintopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_module.practicemaintopic')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemtitle', models.CharField(max_length=150)),
                ('problemexplanation', models.CharField(max_length=1000)),
                ('problemcontstraints', models.CharField(max_length=50)),
                ('sampleinput', models.CharField(max_length=500)),
                ('sampleoutput', models.CharField(max_length=500)),
                ('problemtestcaseoneinput', models.CharField(max_length=200)),
                ('problemtestcasetwoinput', models.CharField(max_length=200)),
                ('problemtestcasethreeinput', models.CharField(max_length=200)),
                ('problemtestcaseoneoutput', models.CharField(max_length=200)),
                ('problemtestcasetwooutput', models.CharField(max_length=200)),
                ('problemtestcasethreeoutput', models.CharField(max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_module.practicesubtopic')),
            ],
        ),
    ]
