# Generated by Django 3.1.7 on 2021-03-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproblem',
            name='isbookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
