# Generated by Django 3.1.7 on 2021-03-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0003_auto_20210315_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicemaintopic',
            name='slug',
            field=models.SlugField(default='maintopic', max_length=60),
        ),
    ]
