# Generated by Django 3.1.7 on 2021-03-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0004_practicemaintopic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicemaintopic',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
