# Generated by Django 3.1.7 on 2021-03-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0005_auto_20210315_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicemaintopic',
            name='slug',
            field=models.SlugField(),
        ),
    ]
