# Generated by Django 3.1.7 on 2021-03-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0007_auto_20210315_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesubtopic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
