# Generated by Django 3.1.7 on 2021-03-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0008_practicesubtopic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproblem',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
