# Generated by Django 3.1.7 on 2021-03-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0009_practiceproblem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproblem',
            name='difficulty',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
