# Generated by Django 3.1.7 on 2021-03-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0011_auto_20210322_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproblem',
            name='score',
            field=models.IntegerField(default=20),
        ),
    ]
