# Generated by Django 3.1.7 on 2021-03-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0012_practiceproblem_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=15)),
            ],
        ),
    ]
