# Generated by Django 3.1.7 on 2021-03-23 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0013_difficulty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Difficulty',
            new_name='DifficultyLevel',
        ),
    ]
