# Generated by Django 3.1.7 on 2021-03-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0015_auto_20210323_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=250)),
                ('attempted', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_module.practiceproblem')),
            ],
        ),
    ]
