# Generated by Django 3.1.7 on 2021-03-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0018_auto_20210325_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemcontstraints',
            new_name='problemconstraints',
        ),
    ]
