# Generated by Django 3.1.7 on 2021-03-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0020_auto_20210325_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceproblem',
            name='userestcaseoneoutput',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practiceproblem',
            name='userestcasethreeoutput',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practiceproblem',
            name='userestcasetwooutput',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
