# Generated by Django 3.1.7 on 2021-04-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0025_auto_20210331_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceproblem',
            name='problemconstraints',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='problemtestcaseoneinput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='problemtestcaseoneoutput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='problemtestcasethreeinput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='problemtestcasethreeoutput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='problemtestcasetwoinput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='problemtestcasetwooutput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='sampleinput',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='practiceproblem',
            name='sampleoutput',
            field=models.TextField(max_length=500),
        ),
    ]
