# Generated by Django 3.1.7 on 2021-04-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0026_auto_20210404_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='inputexplanation',
            new_name='input_explanation',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='outputexplanation',
            new_name='output_explanation',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemconstraints',
            new_name='problem_constraints',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemdescription',
            new_name='problem_description',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemexplanation',
            new_name='problem_explanation',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemstatement',
            new_name='problem_statement',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemtestcaseoneinput',
            new_name='problem_testcase_one_input',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemtestcaseoneoutput',
            new_name='problem_testcase_one_output',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemtestcasethreeinput',
            new_name='problem_testcase_three_input',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemtestcasethreeoutput',
            new_name='problem_testcase_three_output',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemtestcasetwoinput',
            new_name='problem_testcase_two_input',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemtestcasetwooutput',
            new_name='problem_testcase_two_output',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='sampleinput',
            new_name='sample_input',
        ),
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='sampleoutput',
            new_name='sample_output',
        ),
    ]
