# Generated by Django 3.1.7 on 2021-04-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_module', '0027_auto_20210410_0137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practiceproblem',
            old_name='problemtitle',
            new_name='problem_title',
        ),
    ]
