# Generated by Django 3.1.7 on 2021-03-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algotitle', models.CharField(max_length=50)),
                ('algocontent', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DSChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dstitle', models.CharField(max_length=50)),
                ('dscontent', models.CharField(max_length=250)),
            ],
        ),
    ]
