# Generated by Django 3.1.7 on 2021-03-30 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcompletedstatus',
            name='tutorialsubtopic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutorial_module.tutorialsubtopic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorialsubtopic',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
