# Generated by Django 3.1.7 on 2021-03-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial_module', '0003_auto_20210330_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcontent',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tutorialcontent',
            name='exampleone',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='tutorialcontent',
            name='exampletwo',
            field=models.TextField(max_length=2000),
        ),
    ]
