# Generated by Django 3.1.7 on 2021-03-28 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('practice_module', '0021_auto_20210326_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompeteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitiontitle', models.CharField(max_length=100)),
                ('competitiondescription', models.TextField(max_length=3000)),
                ('regstartdate', models.DateTimeField()),
                ('regenddate', models.DateTimeField()),
                ('competitionstartdate', models.DateTimeField()),
                ('competitionenddate', models.DateTimeField()),
                ('assessmenttime', models.IntegerField(default=10)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(blank=True)),
                ('posted_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Coding Competition', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Upcoming', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUserCompete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registeredon', models.DateTimeField(default=django.utils.timezone.now)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete_module.competemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OngoingCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endtime', models.DateTimeField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete_module.competemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('completedon', models.DateTimeField(default=django.utils.timezone.now)),
                ('timetaken', models.IntegerField(default=0)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete_module.competemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionOwnProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problemtitle', models.CharField(max_length=150)),
                ('problemdescription', models.CharField(max_length=1000)),
                ('problemstatement', models.CharField(max_length=1000)),
                ('problemexplanation', models.CharField(max_length=1000)),
                ('problemconstraints', models.CharField(max_length=50)),
                ('sampleinput', models.CharField(max_length=500)),
                ('inputexplanation', models.CharField(max_length=1000)),
                ('sampleoutput', models.CharField(max_length=500)),
                ('outputexplanation', models.CharField(max_length=1000)),
                ('problemtestcaseoneinput', models.CharField(max_length=200)),
                ('problemtestcasetwoinput', models.CharField(max_length=200)),
                ('problemtestcasethreeinput', models.CharField(max_length=200)),
                ('problemtestcaseoneoutput', models.CharField(max_length=200)),
                ('problemtestcasetwooutput', models.CharField(max_length=200)),
                ('problemtestcasethreeoutput', models.CharField(max_length=200)),
                ('userestcaseoneoutput', models.CharField(max_length=200)),
                ('userestcasetwooutput', models.CharField(max_length=200)),
                ('userestcasethreeoutput', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete_module.competemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionDefaultProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compete_module.competemodel')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice_module.practiceproblem')),
            ],
        ),
        migrations.AddField(
            model_name='competemodel',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compete_module.status'),
        ),
        migrations.AddField(
            model_name='competemodel',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compete_module.competitiontype'),
        ),
    ]
