# Generated by Django 3.1.7 on 2021-03-28 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competemodel',
            old_name='competitionenddate',
            new_name='competitionendingdate',
        ),
        migrations.RenameField(
            model_name='competemodel',
            old_name='competitionstartdate',
            new_name='competitionstartingdate',
        ),
    ]
