# Generated by Django 3.1.7 on 2021-03-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete_module', '0004_auto_20210328_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionownproblem',
            name='inputexplanation',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='outputexplanation',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemdescription',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemexplanation',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemstatement',
            field=models.TextField(max_length=1000),
        ),
    ]
