# Generated by Django 3.1.7 on 2021-03-31 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete_module', '0005_auto_20210331_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionownproblem',
            name='userestcaseoneoutput',
        ),
        migrations.RemoveField(
            model_name='competitionownproblem',
            name='userestcasethreeoutput',
        ),
        migrations.RemoveField(
            model_name='competitionownproblem',
            name='userestcasetwooutput',
        ),
    ]
