# Generated by Django 3.1.7 on 2021-04-02 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete_module', '0006_auto_20210331_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionDefaultProblem',
        ),
    ]
