# Generated by Django 3.1.7 on 2021-04-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete_module', '0007_delete_competitiondefaultproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionownproblem',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
