# Generated by Django 3.1.7 on 2021-04-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compete_module', '0008_competitionownproblem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemconstraints',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemtestcaseoneinput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemtestcaseoneoutput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemtestcasethreeinput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemtestcasethreeoutput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemtestcasetwoinput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='problemtestcasetwooutput',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='sampleinput',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='competitionownproblem',
            name='sampleoutput',
            field=models.TextField(max_length=500),
        ),
    ]
