# Generated by Django 3.1.7 on 2021-04-08 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compete_module', '0009_auto_20210403_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competemodel',
            old_name='assessmenttime',
            new_name='assessment_time',
        ),
        migrations.RenameField(
            model_name='competemodel',
            old_name='competitiondescription',
            new_name='competition_description',
        ),
        migrations.RenameField(
            model_name='competemodel',
            old_name='competitionenddate',
            new_name='competition_end_date',
        ),
        migrations.RenameField(
            model_name='competemodel',
            old_name='competitionstartdate',
            new_name='competition_start_date',
        ),
        migrations.RenameField(
            model_name='competemodel',
            old_name='competitiontitle',
            new_name='competition_title',
        ),
        migrations.RenameField(
            model_name='competemodel',
            old_name='regenddate',
            new_name='registration_end_date',
        ),
        migrations.RenameField(
            model_name='competemodel',
            old_name='regstartdate',
            new_name='registration_start_date',
        ),
    ]
